In [1]:
import pandas as pd

In [2]:
%ls

baseline.csv                                     solution.ipynb
item-features.csv                                test.csv
sample-submission.csv                            train.csv
solution-1-collaborative-filtering-by-svd.ipynb  user-features.csv

In [3]:
test_path = 'test.csv'
train_path = 'train.csv'
user_features_path = 'user-features.csv'
item_features_path = 'item-features.csv'
sample_submission_path = 'sample-submission.csv'

In [4]:
df_sample_submission = pd.read_csv(sample_submission_path)
print(df_sample_submission['user_id'].nunique())
df_sample_submission.head()

497

,user_id,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,166,172,47,117,192,323,251,195,359,9,...,277,242,292,87,70,88,396,314,193,39
1,26,87,174,88,337,165,25,333,72,265,...,115,243,197,335,431,338,99,177,243,285
2,41,147,147,398,423,288,265,185,127,32,...,202,244,151,163,370,183,28,290,128,128
3,286,420,53,389,38,244,273,335,388,105,...,442,31,376,257,321,425,57,291,358,119
4,108,267,430,82,91,384,398,99,53,396,...,426,84,203,324,262,47,127,131,356,180

In [5]:
df_items = pd.read_csv(item_features_path)
print(df_items['item_id'].nunique(), df_items['item_id'].size)
df_items.head()

444 444

,item_id,0,1,2,3,4,5,6,7,8,...,22,23,24,25,26,27,28,29,30,31
0,35,0.005646,-0.012780,-0.011941,0.016942,-0.004044,0.005566,0.006587,0.005411,-0.024627,...,-0.034090,-0.005673,0.009111,-0.008770,-0.016189,-0.016189,0.003432,-0.009490,-0.009490,0.002416
1,19,0.002530,-0.005726,-0.005350,0.007591,-0.001812,0.002494,0.002951,0.002424,-0.011035,...,-0.015274,-0.002542,0.004082,-0.003929,-0.007254,-0.007254,0.001538,-0.004252,-0.004252,0.001082
2,145,0.001592,-0.003604,-0.003368,0.004778,-0.001141,0.001570,0.001858,0.001526,-0.006946,...,-0.009615,-0.001600,0.002570,-0.002473,-0.004566,-0.004566,0.000968,-0.002677,-0.002677,0.000681
3,36,0.002866,-0.006486,-0.006060,0.008598,-0.002052,0.002825,0.003343,0.002746,-0.012499,...,-0.017301,-0.002879,0.004624,-0.004451,-0.008216,-0.008216,0.001742,-0.004816,-0.004816,0.001226
4,357,0.000602,-0.001362,-0.001273,0.001806,-0.000431,0.000593,0.000702,0.000577,-0.002625,...,-0.003634,-0.000605,0.000971,-0.000935,-0.001726,-0.001726,0.000366,-0.001012,-0.001012,0.000258

In [6]:
df_users = pd.read_csv(user_features_path)
print(df_users['user_id'].nunique(), df_users['user_id'].size)
df_users.head()

497 497

,user_id,0,1,2,3,4,5,6,7,8,...,22,23,24,25,26,27,28,29,30,31
0,0,0.000695,-0.001573,-0.001470,0.002085,-0.000498,0.000685,0.000811,0.000666,-0.003031,...,-0.004196,-0.000698,0.001121,-0.001079,-0.001993,-0.001993,0.000422,-0.001168,-0.001168,0.000297
1,1,0.001204,-0.002725,-0.002546,0.003612,-0.000862,0.001187,0.001404,0.001154,-0.005251,...,-0.007268,-0.001209,0.001942,-0.001870,-0.003451,-0.003451,0.000732,-0.002023,-0.002023,0.000515
2,2,0.000491,-0.001112,-0.001039,0.001475,-0.000352,0.000484,0.000573,0.000471,-0.002144,...,-0.002967,-0.000494,0.000793,-0.000763,-0.001409,-0.001409,0.000299,-0.000826,-0.000826,0.000210
3,3,0.000777,-0.001759,-0.001643,0.002332,-0.000557,0.000766,0.000906,0.000745,-0.003389,...,-0.004691,-0.000781,0.001254,-0.001207,-0.002228,-0.002228,0.000472,-0.001306,-0.001306,0.000332
4,4,0.000695,-0.001573,-0.001470,0.002085,-0.000498,0.000685,0.000811,0.000666,-0.003031,...,-0.004196,-0.000698,0.001121,-0.001079,-0.001993,-0.001993,0.000422,-0.001168,-0.001168,0.000297

In [7]:
df_train = pd.read_csv(train_path)
df_train.head()

   user_id  item_id  like   timestamp
0      140      342     0  1490936622
1      378      172     1  1490936628
2      150      182     0  1490936650
3      455       17     0  1490936704
4      350      409     0  1490936735

In [8]:
df_test = pd.read_csv(test_path)
print(df_test['user_id'].size, df_test['user_id'].nunique())
df_test.head()

497 497

   user_id   timestamp
0      166  1490944431
1       26  1490957371
2       41  1490958147
3      286  1490971255
4      108  1490976836

In [10]:
import numpy as np
disliked = np.unique(np.sort(df_train[df_train['like'] == 0]['item_id'].values))
liked = np.unique(np.sort(df_train[df_train['like'] == 1]['item_id'].values))

In [25]:
import matplotlib.pyplot as plt
#plt.matshow(df_items.corr())
#plt.show()
df_items.corr()

,item_id,0,1,2,3,4,5,6,7,8,...,22,23,24,25,26,27,28,29,30,31
item_id,1.000000,-0.097309,0.035754,0.125353,-0.135129,0.058163,-0.079583,-0.085037,0.020312,0.282643,...,0.148444,0.019534,-0.058717,0.057614,0.128786,0.128786,-0.085482,0.095636,0.095636,-0.068252
0,-0.097309,1.000000,0.080587,-0.047669,-0.394088,0.309165,0.176628,0.414068,-0.532722,0.361427,...,-0.457159,-0.032988,0.549128,-0.266203,-0.214396,-0.214396,-0.161576,0.053562,0.053562,0.221997
1,0.035754,0.080587,1.000000,-0.430568,-0.532464,-0.410484,-0.634535,-0.562737,0.598375,-0.259717,...,0.469019,0.615415,-0.631476,-0.048127,-0.350353,-0.350353,-0.228374,0.337325,0.337325,-0.630255
2,0.125353,-0.047669,-0.430568,1.000000,-0.172161,0.764807,-0.246189,-0.006940,-0.144826,-0.089080,...,-0.561359,-0.736709,0.223955,-0.303094,-0.253037,-0.253037,-0.497777,0.467211,0.467211,-0.195389
3,-0.135129,-0.394088,-0.532464,-0.172161,1.000000,-0.220688,0.504038,0.456306,-0.152208,-0.076064,...,0.268515,-0.182854,0.163650,0.025314,0.422607,0.422607,0.370715,-0.287570,-0.287570,0.509028
4,0.058163,0.309165,-0.410484,0.764807,-0.220688,1.000000,0.006071,0.377047,-0.591446,-0.117341,...,-0.754438,-0.504361,0.640220,-0.297332,-0.244417,-0.244417,-0.417635,0.363841,0.363841,0.044700
5,-0.079583,0.176628,-0.634535,-0.246189,0.504038,0.006071,1.000000,0.643134,-0.704107,0.419350,...,-0.162641,0.067314,0.687697,0.211219,0.463704,0.463704,0.722961,-0.735218,-0.735218,0.984367
6,-0.085037,0.414068,-0.562737,-0.006940,0.456306,0.377047,0.643134,1.000000,-0.887764,0.299729,...,-0.290127,-0.164072,0.867125,-0.295063,0.250094,0.250094,0.088106,-0.309321,-0.309321,0.647862
7,0.020312,-0.532722,0.598375,-0.144826,-0.152208,-0.591446,-0.704107,-0.887764,1.000000,-0.376918,...,0.532488,0.153573,-0.987673,0.156355,-0.193934,-0.193934,-0.137758,0.333939,0.333939,-0.710724
8,0.282643,0.361427,-0.259717,-0.089080,-0.076064,-0.117341,0.419350,0.299729,-0.376918,1.000000,...,0.086836,-0.013579,0.318527,0.022428,0.347456,0.347456,0.107202,-0.420319,-0.420319,0.427658
9,0.282643,0.361427,-0.259717,-0.089080,-0.076064,-0.117341,0.419350,0.299729,-0.376918,1.000000,...,0.086836,-0.013579,0.318527,0.022428,0.347456,0.347456,0.107202,-0.420319,-0.420319,0.427658
10,-0.217051,0.435541,-0.463101,0.624483,-0.167722,0.624808,0.013461,0.236161,-0.358796,-0.076478,...,-0.821875,-0.769484,0.441554,-0.340121,-0.243468,-0.243468,-0.253658,0.238782,0.238782,0.020582
11,0.015076,-0.036030,-0.584920,0.785756,0.129701,0.523802,-0.147277,0.127873,-0.114655,-0.008437,...,-0.457647,-0.983356,0.183026,-0.325040,-0.005156,-0.005156,-0.406512,0.410073,0.410073,-0.126683
12,-0.043200,-0.518355,0.583624,-0.125290,-0.149640,-0.109766,-0.491134,-0.529634,0.537579,-0.791838,...,0.280807,0.465234,-0.544787,0.089115,-0.306759,-0.306759,-0.029342,0.275325,0.275325,-0.519234
13,-0.003035,-0.430932,0.087022,-0.047232,-0.009138,-0.404001,-0.075854,-0.620292,0.518400,0.017953,...,0.403991,0.102365,-0.466387,0.509330,0.191870,0.191870,0.074289,-0.064901,-0.064901,-0.026879
14,-0.046839,0.280371,0.316146,0.003804,-0.038600,-0.030507,-0.479757,0.232955,0.077141,0.013511,...,0.148351,-0.089992,-0.092507,-0.634897,-0.302435,-0.302435,-0.637010,0.351873,0.351873,-0.460893
15,0.088685,0.507644,-0.027315,0.242988,-0.490015,0.118322,-0.104254,-0.038201,-0.093428,0.449886,...,-0.445632,-0.121960,0.113825,0.013974,-0.250602,-0.250602,-0.172493,-0.002449,-0.002449,-0.074125
16,0.015668,0.022290,0.155285,0.180256,-0.441437,0.310656,-0.320033,-0.354807,0.149959,-0.452627,...,-0.418236,-0.176553,-0.138487,0.220127,-0.118341,-0.118341,-0.014366,0.419132,0.419132,-0.361119
17,0.033520,-0.128220,0.079309,-0.282970,0.144985,-0.130808,-0.027180,-0.100306,0.148491,-0.321190,...,0.027040,0.055978,-0.152542,0.569634,0.343952,0.343952,0.249517,0.224168,0.224168,-0.028404
18,0.004130,-0.083608,-0.581498,0.005391,0.545679,0.214731,0.669206,0.482183,-0.504824,0.068029,...,-0.092345,-0.288575,0.492031,0.014639,0.478239,0.478239,0.478958,-0.241576,-0.241576,0.640441
19,0.004130,-0.083608,-0.581498,0.005391,0.545679,0.214731,0.669206,0.482183,-0.504824,0.068029,...,-0.092345,-0.288575,0.492031,0.014639,0.478239,0.478239,0.478958,-0.241576,-0.241576,0.640441
20,-0.003774,-0.262835,-0.145058,-0.517056,0.293102,-0.407316,0.567982,0.033795,-0.068149,0.023246,...,0.123118,0.367953,0.010856,0.529408,0.468879,0.468879,0.907810,-0.583273,-0.583273,0.485801
21,0.118716,-0.140542,0.334109,-0.194994,-0.175598,-0.290127,0.097140,-0.551651,0.332807,-0.036085,...,0.291340,0.409213,-0.305086,0.484370,0.080403,0.080403,0.421975,-0.026988,-0.026988,0.147488
22,0.148444,-0.457159,0.469019,-0.561359,0.268515,-0.754438,-0.162641,-0.290127,0.532488,0.086836,...,1.000000,0.452747,-0.587472,0.183872,0.384512,0.384512,0.058637,-0.025581,-0.025581,-0.150799
23,0.019534,-0.032988,0.615415,-0.736709,-0.182854,-0.504361,0.067314,-0.164072,0.153573,-0.013579,...,0.452747,1.000000,-0.236436,0.245673,-0.070993,-0.070993,0.372249,-0.412518,-0.412518,0.027242
24,-0.058717,0.549128,-0.631476,0.223955,0.163650,0.640220,0.687697,0.867125,-0.987673,0.318527,...,-0.587472,-0.236436,1.000000,-0.143982,0.175281,0.175281,0.098917,-0.261166,-0.261166,0.713022
25,0.057614,-0.266203,-0.048127,-0.303094,0.025314,-0.297332,0.211219,-0.295063,0.156355,0.022428,...,0.183872,0.245673,-0.143982,1.000000,0.607863,0.607863,0.369521,-0.151939,-0.151939,0.237724
26,0.128786,-0.214396,-0.350353,-0.253037,0.422607,-0.244417,0.463704,0.250094,-0.193934,0.347456,...,0.384512,-0.070993,0.175281,0.607863,1.000000,1.000000,0.287579,-0.187989,-0.187989,0.488978
27,0.128786,-0.214396,-0.350353,-0.253037,0.422607,-0.244417,0.463704,0.250094,-0.193934,0.347456,...,0.384512,-0.070993,0.175281,0.607863,1.000000,1.000000,0.287579,-0.187989,-0.187989,0.488978
28,-0.085482,-0.161576,-0.228374,-0.497777,0.370715,-0.417635,0.722961,0.088106,-0.137758,0.107202,...,0.058637,0.372249,0.098917,0.369521,0.287579,0.287579,1.000000,-0.749934,-0.749934,0.650238
29,0.095636,0.053562,0.337325,0.467211,-0.287570,0.363841,-0.735218,-0.309321,0.333939,-0.420319,...,-0.025581,-0.412518,-0.261166,-0.151939,-0.187989,-0.187989,-0.749934,1.000000,1.000000,-0.639642
30,0.095636,0.053562,0.337325,0.467211,-0.287570,0.363841,-0.735218,-0.309321,0.333939,-0.420319,...,-0.025581,-0.412518,-0.261166,-0.151939,-0.187989,-0.187989,-0.749934,1.000000,1.000000,-0.639642
31,-0.068252,0.221997,-0.630255,-0.195389,0.509028,0.044700,0.984367,0.647862,-0.710724,0.427658,...,-0.150799,0.027242,0.713022,0.237724,0.488978,0.488978,0.650238,-0.639642,-0.639642,1.000000

In [12]:
# Aproach 1: Model-based collaborative filtering system
# Baseline: don't consider user/item features at all
# Source: https://www.kaggle.com/shawamar/product-recommendation-system-for-e-commerce
df_train_mod = df_train
df_train_mod['like'] = np.where(df_train_mod['like'] == 1, 1, -1)
utility_mat = df_train_mod.pivot_table(values='like', index='user_id', columns='item_id', fill_value=0)
X = utility_mat.T
print(X.shape)
X.head()

(444, 497)

user_id,0,1,2,3,4,5,6,7,8,9,...,487,488,489,490,491,492,493,494,495,496
item_id,,,,,,,,,,,,,,,,,,,,,
0,0,-1,0,0,0,-1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
from sklearn.decomposition import TruncatedSVD

SVD = TruncatedSVD(n_components=10)
decomposed_matrix = SVD.fit_transform(X)
print(decomposed_matrix.shape)
#decomposed_matrix

(444, 10)

In [14]:
import numpy as np

correlation_matrix = np.corrcoef(decomposed_matrix)
print(correlation_matrix.shape)
#correlation_matrix

(444, 444)

In [17]:
item_id = 42
correlation_product_ID = correlation_matrix[item_id]
print(correlation_product_ID.shape)
#correlation_product_ID

(444,)

In [18]:
Recommend = list(X.index[correlation_product_ID > 0.7])
Recommend

[27, 42, 46, 153, 218, 230, 260, 262, 264, 265, 276, 355]

In [19]:
# {user, [(liked_item_0, time), ... ]}
user_old_preferences_dct = dict()
for index, row in df_train[df_train['like'] == 1].iterrows():
    user_id, item_id, time = row['user_id'], row['item_id'], row['timestamp']
    if user_id not in user_old_preferences_dct:
        user_old_preferences_dct[user_id] = [(item_id, time)]
    else:
        user_old_preferences_dct[user_id].append((item_id, time))

In [20]:
def get_top_k_simular_to(items, blacklist, k):
    res = []
    for item_id in items:
        for other_item_id, corr_score in enumerate(correlation_matrix[item_id]):
            if other_item_id not in blacklist:
                res.append((other_item_id, corr_score))
    res_sorted_by_score = sorted(res, key=lambda t: t[1], reverse=True)
    if len(res_sorted_by_score) < k:
        raise
    return res_sorted_by_score[0:k]

In [21]:
user_predicted_preferences_dct = dict()
for index, row in df_test.iterrows():
    user_id, timestamp = row['user_id'], row['timestamp']
    all_preferences = [t[0] for t in user_old_preferences_dct[user_id]]
    blacklist = [t[0] for t in user_old_preferences_dct[user_id] if t[1] < timestamp]
    user_predicted_preferences_dct[user_id] = get_top_k_simular_to(all_preferences, blacklist, 20)
#user_predicted_preferences_dct

In [22]:
user_predicted_lists = dict()
for user_id, scored_values in user_predicted_preferences_dct.items():
    user_predicted_lists[user_id] = [t[0] for t in scored_values]
#user_predicted_lists

In [23]:
df_subb = pd.DataFrame(user_predicted_lists).T
df_subb.index.rename('user_id', inplace=True)
#df_subb.to_csv("baseline.csv")
df_subb.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
user_id,,,,,,,,,,,,,,,,,,,,
166,63,155,32,95,44,138,36,70,78,118,137,17,59,90,88,146,148,34,30,61
26,126,111,15,49,81,110,21,26,83,28,366,73,109,395,397,87,104,398,144,396
41,19,99,88,104,324,38,373,59,22,128,49,146,102,36,323,26,61,112,172,377
286,80,145,58,60,161,72,65,35,22,68,160,147,11,66,150,37,424,77,76,122
108,147,145,150,77,161,40,11,164,68,58,35,80,60,72,37,148,160,122,158,56